// This file was automatically generated by typings-for-css-module-loader

export const backdrop: string;
export const display: string;
export const category: string;
export const sub: string;
export const item: string;
export const invisible: string;
