// This file was automatically generated by typings-for-css-module-loader

export const header: string;
export const menuBtn: string;
export const menu: string;
export const display: string;
export const item: string;
export const invisible: string;
