// This file was automatically generated by typings-for-css-module-loader

export const icon: string;
export const absent: string;
export const present: string;
export const ready: string;
export const loading: string;
