const path = require('path');

module.exports = {
  entry: './src/index.tsx',
  resolve: {
    extensions: [".ts", ".tsx", ".js"]
  },
  output: {
    filename: 'main.js',
  },
  module: {
    rules: [
      {
        test: /\.s?css$/,
        loader: 'style-loader',
      },
      {
        test: /\.s?css$/,
        exclude: /\.mod\.s?css$/,
        loader: 'css-loader',
      },
      {
        test: /\.mod\.s?css$/,
        use: {
          loader: 'typings-for-css-modules-loader',
          options: {
            modules: true,
            camelCase: true,
            namedExport: true,
            banner: '// This file was automatically generated by typings-for-css-module-loader\n',
          },
        },
      },
      {
        test: /\.scss$/,
        loader: 'sass-loader',
      },
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
      },
    ],
  },
};
