// This file was automatically generated by typings-for-css-module-loader

export const badge: string;
export const twos: string;
export const threes: string;
export const fours: string;
export const kinder: string;
