// This file was automatically generated by typings-for-css-module-loader

export const listPane: string;
export const header: string;
export const menuBtn: string;
export const content: string;
export const pane: string;
