// This file was automatically generated by typings-for-css-module-loader

export const header: string;
export const headerDark: string;
export const headerLight: string;
export const icon: string;
export const text: string;
export const subheader: string;
export const subheaderDark: string;
export const subheaderLight: string;
