// This file was automatically generated by typings-for-css-module-loader

export const classChooser: string;
export const visible: string;
export const hidden: string;
export const title: string;
export const btnRow: string;
