// This file was automatically generated by typings-for-css-module-loader

export const optionOverlay: string;
export const title: string;
export const btnRow: string;
export const draggable: string;
export const droppable: string;
export const target: string;
